name: Biomodel Store Update Workflow
run-name: ${{ github.actor }} is updating the biomodel store
# Update twice a month, on the 1st and 15th
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 1 * *'
jobs:
  update-biomodel-store:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run caching code
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          python3 biomodels.py
      - name: Check in updated and new SBML biomodels
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "Updated cached sbml biomodels " 
          git push
  
